### ISSUE TITLE
Unable to open serial port /dev/ttyACM0

### ISSUE THREAD

**Issue by joelmaranhao** [simondlevy/BreezyLidar#3]
On Ubuntu 14.04 with URG-04LX (Hokuyo Automatic Co.,Ltd.)
and Python 2.7.6

```
~/BreezyLidar/examples$ ./urgtest.py 

breezylidar.URG04LX:hokuyo_connect:_connect: serial_device_connect: Unable to open serial port /dev/ttyACM0
breezylidar.URG04LX:hokuyo_connect:_connect: failed
Traceback (most recent call last):
  File "./urgtest.py", line 30, in <module>
    laser = URG04LX(DEVICE)

```

but the device is there and it's scanning

```
~/BreezyLidar/examples$ ls -al /dev/ttyACM0 
crw-rw---- 1 root dialout 166, 0 Jun 23 16:14 /dev/ttyACM0
```

Trying with `sudo`:

```
~/BreezyLidar/examples$ sudo ./urgtest.py 

breezylidar.URG04LX:hokuyo_connect:_connect:_get_sensor_info: response does not match:
breezylidar.URG04LX:hokuyo_connect:_connect:_get_sensor_info_and_params: unable to get status!
breezylidar.URG04LX:hokuyo_connect:_connect: could not get status data from sensor
Traceback (most recent call last):
  File "./urgtest.py", line 30, in <module>
    laser = URG04LX(DEVICE)
TypeError: Wrong/insufficient arguments passed to URG04LX.__init__() 
```
# `lsusb --verbose`

```
Bus 001 Device 010: ID 15d1:0000  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            2 Communications
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x15d1 
  idProduct          0x0000 
  bcdDevice            1.00
  iManufacturer           1 Hokuyo Data Flex for USB
  iProduct                2 URG-Series USB Driver
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           67
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface              0 
      CDC Header:
        bcdCDC               1.10
      CDC ACM:
        bmCapabilities       0x06
          sends break
          line coding and serial state
      CDC Union:
        bMasterInterface        0
        bSlaveInterface         1 
      CDC Call Management:
        bmCapabilities       0x03
          call management
          use DataInterface
        bDataInterface          1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval              16
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
```

any pointers?

Cheers

**Comment by simondlevy** [comment]
Joel,

Are you part of the dialout group?  You check this with a Linux command:

  % groups

If you don't see dialout, you should add yourself to the group:

  % sudo usermod -a -G dialout $USER

**Comment by joelmaranhao** [comment]
`otto` is my user

```
$ groups
otto adm cdrom sudo dip plugdev lpadmin sambashare
```

`dialout` is not there

So I have ran your command

```
$ more /etc/group | grep dialout
dialout:x:20:otto
```

But if I run the `groups` command, `dialout` still doesn't show.

So I probably need to do something extra.

# UPDATE 1

I need to **logout** and **login** 

here you go

```
$ groups
otto adm dialout cdrom sudo dip plugdev lpadmin sambashare
```

So why do I need to be in the `dialout` group?
